server:
  port: 8081

spring:
  redis:
    host: 192.168.137.141   #redis服务器地址
    port: 6379              #redis服务器端口号
    password: 123456        #redis密码
    timeout: 300000          #连接超时时间
    database: 0             #Redis数据库索引（默认为0）
